server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s


polar:
  greetingMessage: Hello Anand
  testData:
    enabled: true


spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    confifg:
      uri: http://localhost:8888
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
#  sql:
#    init:
#      mode: always
  profiles:
    active: testData


management:
  endpoints:
    web:
      exposure:
        include: refresh